const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { createFamilyServer } = require('../server.cjs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const p = (id, parent) => ({ id, name: id, gender: 'M', location: '', position: '', siblingOrder: null, relationships: parent ? [{ type: 'parent', personId: parent, kind: '親生' }] : [] });
(async () => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'kinship-ui-'));
  const dataFile = path.join(dir, 'family.json');
  const initial = JSON.stringify({ schemaVersion: 2, people: [p('G'), p('P', 'G'), p('Q', 'G'), p('A', 'P'), p('B', 'Q'), p('X')] });
  await fs.writeFile(dataFile, initial);
  const server = createFamilyServer({ dataFile });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
    const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    async function choose(selector, value) {
      const select = page.locator(selector);
      const label = await select.locator('option').evaluateAll((options, value) => options.find(o => o.value === value).textContent, value);
      await select.locator('..').locator('.select-trigger').click();
      await page.locator('.select-dropdown:popover-open input').fill(label);
      await page.locator('.select-dropdown:popover-open [role=option]').filter({ hasText: label }).first().click();
    }
    let fail = true;
    await page.route('**/data/kinship-terms.json', async route => fail ? route.fulfill({ status: 500, body: '{}' }) : route.continue());
    await page.goto('http://127.0.0.1:' + server.address().port);
    await page.waitForFunction(() => document.querySelectorAll('.person').length === 6);
    assert.equal(await page.locator('.generation[data-uncertain=true] .person').getAttribute('data-person-id'), 'X');
    assert.equal(await page.locator('.generation[data-uncertain=true]').getAttribute('data-gen'), '4');
    assert.equal(await page.locator('.tree__generation-label-track[data-uncertain=true]').textContent(), '未確定');
    assert.equal(await page.locator('.generation[data-gen="1"] .person').getAttribute('data-person-id'), 'G');
    await page.locator('#kinship-retry').waitFor({ state: 'visible' });
    fail = false; await page.click('#kinship-retry');
    await page.waitForFunction(() => document.querySelector('#kinship-status').textContent === '');
    const originalGraph = await page.evaluate(() => JSON.stringify(FAMILY));
    await page.click('#toggle-canvas-names');
    assert.equal(await page.locator('#toggle-canvas-names').getAttribute('aria-pressed'), 'true');
    assert.ok(await page.locator('.person__name').evaluateAll(nodes => nodes.every(n => n.textContent === 'OOO')));
    assert.equal(await page.evaluate(() => JSON.stringify(FAMILY)), originalGraph);
    assert.equal(await page.locator('#relationship-a option[value=A]').textContent(), 'A');
    await page.evaluate(() => window.selectFamilyMember('A'));
    assert.match(await page.locator('#relationship-details-title').textContent(), /A的關係/);
    await choose('#relationship-a', 'A'); await choose('#relationship-b', 'B');
    const desktopFields = await page.locator('.relationship-field-a,.relationship-field-b,#relationship-swap').evaluateAll(nodes => nodes.map(n => ({ id: n.id || n.className, x: n.getBoundingClientRect().x })));
    assert(desktopFields[0].x < desktopFields[1].x && desktopFields[1].x < desktopFields[2].x);
    await page.click('#relationship-search [type=submit]');
    assert.match(await page.locator('#relationship-summary h2').textContent(), /A 為 B 的堂兄弟/);
    assert.deepEqual((await page.locator('.person').evaluateAll(nodes => nodes.map(n => n.dataset.personId))).sort(), ['A', 'B', 'G', 'P', 'Q']);
    assert.equal(await page.locator('#family-filter').isDisabled(), true);
    assert.equal(await page.locator('.pair-a').count(), 1);
    assert.equal(await page.locator('.generation[data-uncertain=true]').count(), 0);
    assert.ok(await page.locator('.person__name').evaluateAll(nodes => nodes.every(n => n.textContent === 'OOO')));
    await page.click('#toggle-canvas-names');
    assert.deepEqual((await page.locator('.person__name').allTextContents()).sort(), ['A', 'B', 'G', 'P', 'Q']);
    const before = await page.locator('#relationship-summary').boundingBox();
    await page.locator('.tree').evaluate(node => { node.scrollTop = 100; node.scrollLeft = 100; });
    assert.deepEqual(await page.locator('#relationship-summary').boundingBox(), before);
    await page.click('#relationship-swap');
    assert.match(await page.locator('#relationship-summary h2').textContent(), /B 為 A 的堂兄弟/);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(250);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    const headingBox = await page.locator('#relationship-summary h2').boundingBox(), editBox = await page.locator('#relationship-result-edit').boundingBox();
    assert(editBox.x >= headingBox.x + headingBox.width, 'modify sits beside the summary');
    await page.evaluate(() => window.selectFamilyMember('A'));
    assert.equal(await page.locator('#relationship-details').getAttribute('data-collapsed'), 'true');
    assert((await page.locator('#relationship-details').boundingBox()).height <= 56);
    await page.click('.relationship-details__tab');
    assert.equal(await page.locator('#relationship-details').getAttribute('data-collapsed'), 'false');
    assert((await page.locator('#relationship-details').boundingBox()).height <= 844 * .48 + 1);
    for (const width of [320, 390]) {
      await page.setViewportSize({ width, height: 844 });
      await page.waitForTimeout(200);
      const contained = await page.locator('#relationship-details').evaluate(panel => {
        const r = panel.getBoundingClientRect();
        return [...panel.querySelectorAll('.relationship-details__header button')].every(b => { const box = b.getBoundingClientRect(); return box.left >= r.left && box.right <= r.right && box.top >= r.top && box.bottom <= r.bottom; });
      });
      assert(contained, 'detail header buttons remain inside panel');
    }
    await page.evaluate(() => window.selectFamilyMember('B'));
    assert.equal(await page.locator('#relationship-details').getAttribute('data-collapsed'), 'true');
    await page.click('.relationship-details__tab');
    await page.click('.details-close');
    await page.screenshot({ path: path.join(dir, 'mobile.png') });
    await page.click('#relationship-result-edit');
    assert.equal(await page.locator('.relationship-sheet').evaluate(d => d.open), true);
    const fieldB = await page.locator('.relationship-field-b').boundingBox(), fieldA = await page.locator('.relationship-field-a').boundingBox();
    assert(fieldB.y < fieldA.y); assert(fieldB.width > 300);
    const swapBox = await page.locator('#relationship-swap').boundingBox();
    assert(Math.abs(swapBox.x + swapBox.width / 2 - (fieldB.x + fieldB.width / 2)) < 1);
    assert.equal(await page.locator('#relationship-swap svg').count(), 1);
    if (process.env.SEARCH_SHEET_SCREENSHOT) await page.screenshot({ path: process.env.SEARCH_SHEET_SCREENSHOT });
    await choose('#relationship-a', 'X');
    await page.click('#relationship-sheet-close');
    assert.equal(await page.locator('#relationship-a').inputValue(), 'B', 'cancel restores previous query');
    await page.click('#relationship-result-edit');
    await choose('#relationship-a', 'X'); await page.click('#relationship-search [type=submit]');
    assert.equal(await page.locator('.relationship-sheet').evaluate(d => d.open), false);
    assert.equal(await page.locator('.person').count(), 2);
    assert.match(await page.locator('#relationship-summary').textContent(), /尚無已記錄/);
    await page.click('#relationship-result-edit');
    await choose('#relationship-b', 'X'); await page.click('#relationship-search [type=submit]');
    assert.equal(await page.locator('.person').count(), 1);
    assert.equal(await page.locator('.generation').count(), 1);
    assert.equal(await page.locator('.tree__generation-label').textContent(), '未確定');
    await page.click('.relationship-result-end');
    assert.equal(await page.locator('.person').count(), 6);
    assert.equal(await page.locator('#relationship-summary').isHidden(), true, 'mobile relationship summary disappears when comparison ends');
    assert.equal(await page.locator('#relationship-summary').getAttribute('class'), 'relationship-summary', 'compact display class is cleared after comparison ends');
    await page.setViewportSize({ width: 1440, height: 960 });
    assert.equal(await page.locator('.select-dropdown:popover-open').count(), 0);
    await page.locator('#relationship-a').locator('..').locator('.select-trigger').click();
    await page.locator('.select-dropdown:popover-open input').fill('不存在');
    assert.match(await page.locator('.select-dropdown:popover-open').textContent(), /找不到符合/);
    await page.locator('.select-dropdown:popover-open input').fill('X');
    assert.equal(await page.locator('.select-dropdown:popover-open [role=option]').count(), 1);
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('#relationship-a').inputValue(), 'X');
    assert.equal(await page.locator('.select-dropdown:popover-open').count(), 0);
    await page.click('#show-member-list');
    assert.equal(await page.locator('#member-list-body tr').count(), 6);
    assert.equal(await page.locator('#member-list-body .member-list-unlinked').count(), 1);
    assert.equal(await page.locator('#member-list-body tr[data-person-id="X"] td').nth(3).textContent(), '');
    assert.equal(await page.locator('#member-list-body tr[data-person-id="G"] td').nth(3).textContent(), '第 1 代');
    await page.keyboard.press('Escape');
    await page.click('#add-member'); await page.click('#add-relation');
    await choose('.relation-row:last-child .relation-target', 'X');
    await choose('.relation-row:last-child .relation-type', 'parent');
    assert.equal(await page.locator('.relation-kind').locator('..').locator('.select-trigger').isVisible(), true);
    await choose('.relation-row:last-child .relation-kind', '養子女');
    await choose('.relation-row:last-child .relation-type', 'teacher');
    assert.equal(await page.locator('.relation-kind').locator('..').locator('.select-trigger').isVisible(), false);
    await page.click('#cancel-member');
    await page.evaluate(() => window.editFamilyMember('A'));
    await page.locator('.relation-target').first().locator('..').locator('.select-trigger').click();
    await page.locator('.select-dropdown:popover-open input').fill('Q');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#member-dialog').evaluate(d => d.open), true);
    assert.equal(await page.locator('.select-dropdown:popover-open').count(), 0);
    await choose('.relation-target', 'Q');
    assert.equal(await page.locator('.relation-target').inputValue(), 'Q');
    await page.click('#cancel-member');
    assert.equal(await fs.readFile(dataFile, 'utf8'), initial);
    assert.deepEqual(errors, []);
    console.log('PASS: config retry, cousin intermediates, reverse, fixed hint, mobile, disconnected, self, reset; data unchanged. Screenshot: ' + path.join(dir, 'mobile.png'));
  } finally { await browser?.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
