const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { createFamilyServer } = require('../server.cjs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const p = (id, parent) => ({ id, name: id, gender: 'M', location: '', position: '', siblingOrder: null, relationships: parent ? [{ type: 'parent', personId: parent, kind: '親生' }] : [] });
(async () => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'kinship-ui-'));
  const dataFile = path.join(dir, 'family.json');
  const initial = JSON.stringify({ schemaVersion: 2, people: [p('G'), p('P', 'G'), p('Q', 'G'), p('A', 'P'), p('B', 'Q'), p('X')] });
  await fs.writeFile(dataFile, initial);
  const server = createFamilyServer({ dataFile });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
    const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    async function choose(selector, value) {
      const select = page.locator(selector);
      const label = await select.locator('option').evaluateAll((options, value) => options.find(o => o.value === value).textContent, value);
      await select.locator('..').locator('.select-trigger').click();
      await page.locator('.select-dropdown:popover-open input').fill(label);
      await page.locator('.select-dropdown:popover-open [role=option]').filter({ hasText: label }).first().click();
    }
    let fail = true;
    await page.route('**/data/kinship-terms.json', async route => fail ? route.fulfill({ status: 500, body: '{}' }) : route.continue());
    await page.goto('http://127.0.0.1:' + server.address().port);
    await page.waitForFunction(() => document.querySelectorAll('.person').length === 6);
    await page.locator('#kinship-retry').waitFor({ state: 'visible' });
    fail = false; await page.click('#kinship-retry');
    await page.waitForFunction(() => !document.querySelector('#relationship-search [type=submit]').disabled);
    await choose('#relationship-a', 'A'); await choose('#relationship-b', 'B');
    await page.click('#relationship-search [type=submit]');
    assert.match(await page.locator('#relationship-summary h2').textContent(), /A 為 B 的堂兄弟/);
    assert.deepEqual((await page.locator('.person').evaluateAll(nodes => nodes.map(n => n.dataset.personId))).sort(), ['A', 'B', 'G', 'P', 'Q']);
    assert.equal(await page.locator('#family-filter').isDisabled(), true);
    assert.equal(await page.locator('.pair-a').count(), 1);
    const before = await page.locator('#relationship-summary').boundingBox();
    await page.locator('.tree').evaluate(node => { node.scrollTop = 100; node.scrollLeft = 100; });
    assert.deepEqual(await page.locator('#relationship-summary').boundingBox(), before);
    await page.click('#relationship-swap');
    assert.match(await page.locator('#relationship-summary h2').textContent(), /B 為 A 的堂兄弟/);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(250);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(dir, 'mobile.png') });
    await choose('#relationship-a', 'X'); await page.click('#relationship-search [type=submit]');
    assert.equal(await page.locator('.person').count(), 2);
    assert.match(await page.locator('#relationship-summary').textContent(), /尚無已記錄/);
    await choose('#relationship-b', 'X'); await page.click('#relationship-search [type=submit]');
    assert.equal(await page.locator('.person').count(), 1);
    await page.click('#relationship-reset'); assert.equal(await page.locator('.person').count(), 6);
    await page.setViewportSize({ width: 1440, height: 960 });
    assert.equal(await page.locator('.select-dropdown:popover-open').count(), 0);
    await page.locator('#relationship-a').locator('..').locator('.select-trigger').click();
    await page.locator('.select-dropdown:popover-open input').fill('不存在');
    assert.match(await page.locator('.select-dropdown:popover-open').textContent(), /找不到符合/);
    await page.locator('.select-dropdown:popover-open input').fill('X');
    assert.equal(await page.locator('.select-dropdown:popover-open [role=option]').count(), 1);
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('#relationship-a').inputValue(), 'X');
    assert.equal(await page.locator('.select-dropdown:popover-open').count(), 0);
    await page.click('#show-member-list');
    assert.equal(await page.locator('#member-list-body tr').count(), 6);
    assert.equal(await page.locator('#member-list-body .member-list-unlinked').count(), 1);
    assert.equal(await page.locator('#member-list-body tr[data-person-id="X"] td').nth(3).textContent(), '');
    assert.equal(await page.locator('#member-list-body tr[data-person-id="G"] td').nth(3).textContent(), '第 1 代');
    await page.keyboard.press('Escape');
    await page.click('#add-member'); await page.click('#add-relation');
    await choose('.relation-row:last-child .relation-target', 'X');
    await choose('.relation-row:last-child .relation-type', 'parent');
    assert.equal(await page.locator('.relation-kind').locator('..').locator('.select-trigger').isVisible(), true);
    await choose('.relation-row:last-child .relation-kind', '養子女');
    await choose('.relation-row:last-child .relation-type', 'teacher');
    assert.equal(await page.locator('.relation-kind').locator('..').locator('.select-trigger').isVisible(), false);
    await page.click('#cancel-member');
    await page.evaluate(() => window.editFamilyMember('A'));
    await page.locator('.relation-target').first().locator('..').locator('.select-trigger').click();
    await page.locator('.select-dropdown:popover-open input').fill('Q');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#member-dialog').evaluate(d => d.open), true);
    assert.equal(await page.locator('.select-dropdown:popover-open').count(), 0);
    await choose('.relation-target', 'Q');
    assert.equal(await page.locator('.relation-target').inputValue(), 'Q');
    await page.click('#cancel-member');
    assert.equal(await fs.readFile(dataFile, 'utf8'), initial);
    assert.deepEqual(errors, []);
    console.log('PASS: config retry, cousin intermediates, reverse, fixed hint, mobile, disconnected, self, reset; data unchanged. Screenshot: ' + path.join(dir, 'mobile.png'));
  } finally { await browser?.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
