'use strict';
const $=id=>document.getElementById(id);
const iconPaths={people:'<circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M16 5a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 4v2"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7a2 2 0 0 0-4-4L5 15z"/>',relation:'<circle cx="6" cy="6" r="3"/><circle cx="18" cy="18" r="3"/><path d="m8 8 8 8m-3-8h5v5M6 11v7h7"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>','eye-off':'<path d="m3 3 18 18M10.6 5.1A10.9 10.9 0 0 1 12 5c6 0 10 7 10 7a17.5 17.5 0 0 1-3.2 3.9M6.5 6.5C3.7 8.5 2 12 2 12s4 7 10 7a11 11 0 0 0 5.5-1.5M9.9 9.9a3 3 0 0 0 4.2 4.2"/>',legend:'<path d="M9 6h12M9 12h8M9 18h12M3 6h1M3 12h1M3 18h1"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>','chevron-down':'<path d="m6 9 6 6 6-6"/>','chevron-right':'<path d="m9 6 6 6-6 6"/>','chevron-left':'<path d="m15 6-6 6 6 6"/>','person-plus':'<circle cx="9" cy="7" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2m4-10v8m-4-4h8"/>',fit:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M8 8l8 8m0-8-8 8"/>',cloud:'<path d="M7 18h11a4 4 0 0 0 0-8 6 6 0 0 0-11-2 5 5 0 0 0 0 10Z"/>',list:'<path d="M9 5h12M9 12h12M9 19h12M3 5h1M3 12h1M3 19h1"/>',merge:'<path d="M5 3v4c0 5 7 5 7 9v5M19 3v4c0 5-7 5-7 9m-4 1 4 4 4-4"/>',undo:'<path d="M4 5v6h6M4 11a8 8 0 1 1 2 9"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/>',download:'<path d="M12 3v13m-5-5 5 5 5-5M4 17v4h16v-4"/>',check:'<path d="m5 12 4 4L19 6"/>',swap:'<path d="M7 3v16m-4-4 4 4 4-4M17 21V5m-4 4 4-4 4 4"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',refresh:'<path d="M20 6v5h-5M4 18v-5h5m-5-2a8 8 0 0 1 13-6l3 6M4 13l3 6a8 8 0 0 0 13-6"/>',device:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>'};
const svg=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]||iconPaths.info}</svg>`;
function hydrateIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=svg(el.dataset.icon));}
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const person=(id,name,gender,gen,role,position='',parents=[],spouse=null)=>({id,name,gender,gen,role,position,parents,spouse,notes:''});
let people=[person('阿土','陳阿土','M',2,'家族長輩'),person('林','林氏','F',2,'家族長輩'),person('文彬','陳文彬','M',3,'手足排行 1','教師',['阿土','林'],'美雲'),person('秀琴','陳秀琴','F',3,'手足排行 2','',['阿土','林']),person('文德','陳文德','M',3,'手足排行 3','',['阿土','林']),person('美雲','王美雲','F',3,'文彬的配偶','',[],'文彬'),person('建國','陳建國','M',4,'手足排行 1','工程師',['文彬','美雲'],'雅婷'),person('淑芬','陳淑芬','F',4,'手足排行 2','設計師',['文彬','美雲']),person('建民','陳建民','M',4,'手足排行 3','',['文彬','美雲']),person('雅婷','吳雅婷','F',4,'建國的配偶','教師',[],'建國'),person('志明','陳志明','M',null,'未設定關係'),person('黃葉','黃阿葉','F',2,'家族長輩','',[],'阿土'),person('冠廷','陳冠廷','M',null,'未設定關係'),person('建副','陳建國','M',4,'待整理的同名成員','工程師',['文彬','美雲'])];
people.find(p=>p.id==='阿土').spouse='林';people.find(p=>p.id==='林').spouse='阿土';
const positions={阿土:[202,38],林:[440,38],秀琴:[53,243],文彬:[321,243],美雲:[521,243],文德:[704,243],建國:[268,444],淑芬:[528,444]};
let selectedId='阿土',detailHistory=[],selectionOrigin='tree',memberFilter='all',queryActive=false,queryIds=['文彬','阿土'],scale=1,namesHidden=false,editId=null,baseline='',removedRow=null,undoStack=[],selectedVersion=null,toastTimer,queryPath=[];
const getPerson=id=>people.find(p=>p.id===id);
const linked=p=>p.parents.filter(Boolean).length||p.spouse||people.some(q=>q.parents.includes(p.id));
const generation=p=>p.gen?`第 ${p.gen} 代`:'未設定關係';
const saveSnapshot=label=>{undoStack.push({people:JSON.parse(JSON.stringify(people)),label});updateUndo();};
function toast(message,undo=false){clearTimeout(toastTimer);$('toast-text').textContent=message;$('toast-undo').hidden=!undo;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
function updateUndo(){const last=undoStack.at(-1);$('undo-menu').disabled=!last;$('undo-menu').querySelector('small').textContent=last?last.label:'目前沒有修改';}
function closeMenus(){for(const id of ['global-menu','legend-popover','form-menu'])$(id).hidden=true;$('global-more-button').setAttribute('aria-expanded','false');}
function updateBrowserIsolation(){const isolated=innerWidth<=700&&!$('member-browser').hidden;for(const el of [document.querySelector('.app-header'),document.querySelector('.workspace-toolbar'),$('query-result'),$('canvas'),$('inspector')])el.inert=isolated;}
function openDialog(id){closeMenus();$(id).showModal();}
function utility(title,body,actions='',eyebrow='成員管理'){$('utility-title').textContent=title;$('utility-eyebrow').textContent=eyebrow;$('utility-body').innerHTML=body;$('utility-actions').innerHTML=actions||'<button class="button primary" data-close>完成</button>';hydrateIcons($('utility-dialog'));openDialog('utility-dialog');}
function renderMembers(){const keyword=$('member-search').value.trim().toLocaleLowerCase();const matches=people.filter(p=>(memberFilter==='all'||!linked(p))&&[p.name,generation(p),p.position,p.role].join(' ').toLocaleLowerCase().includes(keyword));$('member-total').textContent=people.length;$('member-count').textContent=keyword?`找到 ${matches.length} 位成員`:`${matches.length} 位成員`;$('member-rows').innerHTML=matches.length?matches.map(p=>`<button class="member-row" data-person="${p.id}" data-origin="list" aria-current="${p.id===selectedId}" aria-label="查看${escapeHTML(p.name)}，${generation(p)}"><span class="mini-avatar">${escapeHTML(p.name.slice(-1))}</span><div><strong>${escapeHTML(p.name)}</strong>${p.position?`<small>${escapeHTML(p.position)}</small>`:''}</div><span class="generation">${p.gen?generation(p):'<span class="badge pending">未設定關係</span>'}</span></button>`).join(''):'<div class="empty-state">找不到符合的成員<br><button class="text-button" data-action="clear-search">清除搜尋</button></div>';}
function renderTree(){
  const graph=$('graph'),mobile=innerWidth<=700;
  let entries=Object.entries(positions),lines='';
  if(queryActive){
    const ids=[...new Set(queryPath.length?queryPath:queryIds)].filter(getPerson),width=Math.max(320,$('graph-viewport').clientWidth),step=mobile?164:218;
    graph.style.width=width+'px';graph.style.height=(mobile?Math.max(360,ids.length*step):360)+'px';
    entries=ids.map((id,i)=>[id,mobile?[(width-154)/2,26+i*step]:[(width-(ids.length*154+(ids.length-1)*64))/2+i*step,70]]);
    for(let i=1;i<entries.length;i++){const a=entries[i-1][1],b=entries[i][1];lines+=mobile?`<path d="M${a[0]+77} ${a[1]+108}V${b[1]}"/>`:`<path d="M${a[0]+154} ${a[1]+54}H${b[0]}"/>`;}
    lines=`<svg class="query-connections" style="position:absolute;inset:0;width:100%;height:100%;fill:none;stroke:#93a480;stroke-width:1.5" aria-hidden="true">${lines}</svg>`;
  }else{graph.style.width='880px';graph.style.height='570px';}
  $('tree-nodes').innerHTML=lines+entries.filter(([id])=>getPerson(id)).map(([id,[x,y]])=>{const p=getPerson(id);return `<button class="person-node ${p.gender==='F'?'female':''}" style="left:${x}px;top:${y}px" data-person="${id}" aria-pressed="${id===selectedId}" aria-label="查看${escapeHTML(p.name)}的詳情"><span class="node-avatar">${namesHidden?'·':escapeHTML(p.name.slice(-1))}</span><strong>${namesHidden?'成員':escapeHTML(p.name)}</strong><small>${p.role.includes('排行')?p.role:generation(p)}</small></button>`;}).join('');
  document.querySelector('.connections').style.display=queryActive?'none':'';document.querySelectorAll('.generation-mark').forEach(el=>el.hidden=queryActive);graph.style.background=queryActive?'transparent':'';$('scope').disabled=queryActive;updateBrowserIsolation();
}
function group(title,rows,open=true){if(!rows.length)return '';return `<details class="relationship-group" ${open?'open':''}><summary>${svg('chevron-right')}${title}<span class="count">${rows.length}</span></summary>${rows.map(({p,role,pending})=>`<button class="relative-row" data-person="${p.id}" data-origin="relative"><span class="mini-avatar">${escapeHTML(p.name.slice(-1))}</span><div><strong>${escapeHTML(p.name)}</strong><small>${role}</small></div>${pending?'<span class="badge pending">待確認</span>':''}${svg('chevron-right')}</button>`).join('')}</details>`;}
function renderDetail(){const p=getPerson(selectedId);if(!p){$('inspector').hidden=true;return;}$('profile-name').textContent=p.name;$('profile-avatar').textContent=p.name.slice(-1);$('profile-meta').textContent=`${generation(p)}${p.position?' · '+p.position:p.role?' · '+p.role:''}`;$('detail-back').querySelector('span:last-child').textContent=detailHistory.length?'返回 '+getPerson(detailHistory.at(-1))?.name:'返回成員清單';const parents=p.parents.map(getPerson).filter(Boolean).map(p=>({p,role:p.gender==='M'?'父親':'母親'}));const spouses=people.filter(q=>q.id!==p.id&&(q.id===p.spouse||q.spouse===p.id)).map(q=>({p:q,role:'配偶',pending:q.id==='黃葉'}));const children=people.filter(q=>q.parents.includes(p.id)).map(p=>({p,role:p.role}));const siblings=people.filter(q=>q.id!==p.id&&p.parents.some(id=>id&&q.parents.includes(id))).map(p=>({p,role:p.role}));$('detail-body').innerHTML=group('父母',parents)+group('配偶',spouses)+group('子女',children)+group('手足',siblings,false)+(parents.length||children.length||siblings.length?'<details class="evidence"><summary>關係依據'+svg('chevron-down')+'</summary><p>親子關係為直接記錄；手足依共同父母推導。待確認的關係會保留標記，來源與說明可在編輯時補充。</p></details>':'<p class="helper" style="padding:16px 0">還沒有記錄關係。可以從「新增親屬」開始。</p>')+(p.notes?`<section class="relationship-group"><h3 style="font-size:13px">備註</h3><p class="helper" style="margin-top:8px">${escapeHTML(p.notes)}</p></section>`:'');}
function selectPerson(id,origin='tree'){if(!getPerson(id))return;if(origin==='relative'&&selectedId!==id)detailHistory.push(selectedId);else if(origin!=='relative')detailHistory=[];selectedId=id;if(origin!=='relative')selectionOrigin=origin;$('inspector').hidden=false;$('inspector').classList.remove('collapsed');if(innerWidth<=700)$('member-browser').hidden=true;renderDetail();renderMembers();renderTree();}
function renderAll(){renderMembers();renderTree();renderDetail();populateQuery();updateUndo();}
function setScale(value){scale=Math.max(.35,Math.min(1.5,value));$('graph').style.zoom=scale;$('graph').style.transform='none';$('zoom-number').textContent=Math.round(scale*100)+'%';}
function fit(){setScale(queryActive?1:Math.min(1,Math.max(.35,($('graph-viewport').clientWidth-24)/880)));$('graph-viewport').scrollLeft=0;}
function openMembers(){$('member-browser').hidden=false;renderMembers();updateBrowserIsolation();requestAnimationFrame(()=>$('member-search').focus());}
function populateQuery(){for(const id of ['query-a','query-b']){const value=$(id).value;$(id).innerHTML=people.map(p=>`<option value="${p.id}">${escapeHTML(p.name)} · ${generation(p)}</option>`).join('');$(id).value=getPerson(value)?value:id==='query-a'?queryIds[0]:queryIds[1];}updateQuestion();}
function updateQuestion(){const a=getPerson($('query-a').value),b=getPerson($('query-b').value);$('query-question').textContent=a&&b?`${a.name}是${b.name}的誰？`:'請選兩位成員';}
function openQuery(){populateQuery();if(selectedId&&!queryActive){$('query-b').value=selectedId;if($('query-a').value===selectedId)$('query-a').value=people.find(p=>p.id!==selectedId).id;}updateQuestion();openDialog('query-dialog');}
function relationship(a,b){if(a.id===b.id)return {term:'本人',path:[a.id]};if(b.parents.includes(a.id))return{term:a.gender==='M'?'父親':'母親',path:[a.id,b.id]};if(a.parents.includes(b.id))return{term:a.gender==='M'?'兒子':'女兒',path:[b.id,a.id]};if(a.spouse===b.id||b.spouse===a.id)return{term:'配偶',path:[a.id,b.id]};if(a.parents.some(id=>id&&b.parents.includes(id)))return{term:a.gender==='M'?'兄弟':'姊妹',path:[a.id,a.parents.find(id=>b.parents.includes(id)),b.id]};const middle=a.parents.map(getPerson).find(p=>p?.parents.includes(b.id));if(middle)return{term:a.gender==='M'?'孫子':'孫女',path:[b.id,middle.id,a.id]};const inverse=b.parents.map(getPerson).find(p=>p?.parents.includes(a.id));if(inverse)return{term:a.gender==='M'?'祖父':'祖母',path:[a.id,inverse.id,b.id]};return{term:null,path:[a.id,b.id]};}
function runQuery(){queryIds=[$('query-a').value,$('query-b').value];const a=getPerson(queryIds[0]),b=getPerson(queryIds[1]);const result=relationship(a,b);queryPath=result.path;queryActive=true;$('query-result').hidden=false;$('result-title').textContent=result.term?`${a.name}是${b.name}的${result.term}`:`${a.name}與${b.name}尚無可確認的稱謂`;$('canvas-title').textContent='兩個名字，一段關係';$('canvas-subtitle').textContent='沿著家族的記錄，找到稱呼的依據。';$('query-dialog').close();$('inspector').hidden=true;$('member-browser').hidden=true;selectedId=null;renderTree();fit();}
function relationRow(target='阿土',type='父親',expanded=false){return `<div class="relation-edit-row"><div class="relation-summary"><div><span class="mini-avatar">${escapeHTML(getPerson(target)?.name.slice(-1)||'＋')}</span><strong>${escapeHTML(getPerson(target)?.name||'選擇成員')} · ${type}</strong></div><div><button type="button" class="icon-button" data-action="toggle-relation" aria-label="展開或收合關係設定" aria-expanded="${expanded}">${svg('edit')}</button><button type="button" class="icon-button" data-action="remove-relation" aria-label="移除這筆關係">${svg('trash')}</button></div></div><div class="relation-controls" ${expanded?'':'hidden'}><div class="form-grid"><label>現有成員<select class="relation-target">${people.filter(p=>p.id!==editId).map(p=>`<option value="${p.id}" ${p.id===target?'selected':''}>${escapeHTML(p.name)} · ${generation(p)}</option>`).join('')}</select></label><label>是這位成員的<select class="relation-role">${['父親','母親','配偶','手足','子女'].map(role=>`<option ${role===type?'selected':''}>${role}</option>`).join('')}</select></label></div><p class="relation-preview"></p><details class="relation-advanced"><summary>確認狀態、來源與說明</summary><label>確認狀態<select><option>已確認</option><option>待確認</option></select></label><label>來源<input placeholder="例如：家族訪談"></label><label>說明<textarea rows="2" placeholder="補充這段關係的記錄"></textarea></label></details></div></div>`;}
function formSnapshot(){return JSON.stringify({name:$('edit-name').value,gender:$('edit-gender').value,position:$('edit-position').value,notes:$('edit-notes').value,relations:[...$('edit-relations').children].map(row=>({id:row.querySelector('.relation-target')?.value,role:row.querySelector('.relation-role')?.value,extra:[...row.querySelectorAll('input,textarea,select')].map(el=>el.value)})),ranks:[...document.querySelectorAll('.ranking-fields input')].map(el=>el.value)});}
function updateRelation(row){const target=getPerson(row.querySelector('.relation-target').value),role=row.querySelector('.relation-role').value,name=$('edit-name').value.trim()||'這位新成員';row.querySelector('.relation-summary strong').textContent=target.name+' · '+role;row.querySelector('.relation-preview').textContent=`${target.name}是${name}的${role}。`;}
function openEdit(id=selectedId,relative=false){editId=id;const p=getPerson(id);$('edit-title').textContent=relative?'新增親屬':p?'編輯'+p.name:'新增成員';$('edit-name').value=p?.name||'';$('edit-gender').value=p?.gender||'U';$('edit-position').value=p?.position||'';$('edit-notes').value=p?.notes||'';$('name-error').textContent='';$('edit-name').removeAttribute('aria-invalid');$('form-conflict').hidden=true;$('relation-removal').hidden=true;document.querySelector('.optional-section').open=Boolean(p&&(p.position||p.notes));document.querySelectorAll('.ranking-fields input').forEach(el=>el.value='');const rows=p?[...p.parents.filter(getPerson).map(parent=>relationRow(parent,getPerson(parent).gender==='M'?'父親':'母親')), ...(p.spouse?[relationRow(p.spouse,'配偶')]:[])]:relative?[relationRow(selectedId,'父親',true)]:[];$('edit-relations').innerHTML=rows.join('');hydrateIcons($('edit-dialog'));$('edit-relations').querySelectorAll('.relation-edit-row').forEach(updateRelation);baseline=formSnapshot();$('edit-form').querySelector('[type=submit]').textContent=p?'儲存修改':'儲存成員';openDialog('edit-dialog');}
function requestEditClose(){if(formSnapshot()!==baseline)openDialog('discard-dialog');else $('edit-dialog').close();}
function openConflict(){if($('sync-dialog').open)$('sync-dialog').close();selectedVersion=null;document.querySelectorAll('[data-version]').forEach(b=>b.setAttribute('aria-pressed','false'));$('version-commit').disabled=true;$('version-commit').textContent='選擇要保留的版本';$('version-decision').textContent='請先選擇要保留的版本，再確認取代範圍。';openDialog('conflict-dialog');}
function openRanks(){utility('排行群組',`<p class="intro-copy">同一家庭或師門，分開記錄各自的排行。</p><label>群組名稱<input value="陳阿土與林氏的子女"></label><label>排行類型<select><option>家庭手足</option><option>契手足</option><option>師門</option></select></label><div class="local-state"><span data-icon="info"></span><p class="helper">群組用於排行，不會自動建立親屬關係。</p></div>${['文彬','秀琴','文德'].map((id,i)=>`<label class="rank-row"><input type="checkbox" checked><span>${getPerson(id).name}</span><input type="number" aria-label="${getPerson(id).name}的排行" value="${i+1}" min="1" max="999"></label>`).join('')}`, '<button class="button" data-close>取消</button><button class="button primary" data-action="save-ranks">儲存群組</button>');}
function openMerge(){utility('合併重複成員',`<p class="intro-copy">先選擇兩位成員，再逐欄確認。相同名字不代表同一人。</p><div class="form-grid"><label>保留的成員<select id="merge-keep">${people.map(p=>`<option value="${p.id}" ${p.id==='建國'?'selected':''}>${escapeHTML(p.name)} · ${p.role}</option>`).join('')}</select></label><label>併入後移除的成員<select id="merge-remove">${people.map(p=>`<option value="${p.id}" ${p.id==='建副'?'selected':''}>${escapeHTML(p.name)} · ${p.role}</option>`).join('')}</select></label></div><table class="merge-table"><thead><tr><th>欄位</th><th>要保留的內容</th></tr></thead><tbody><tr><td>姓名</td><td><select><option>陳建國 · 此成員</option><option>陳建國 · 併入的成員</option></select></td></tr><tr><td>職位</td><td><select><option>工程師 · 此成員</option><option>工程師 · 併入的成員</option></select></td></tr></tbody></table><div id="merge-preview" hidden></div>`, '<button class="button" data-close>取消</button><button class="button" data-action="preview-merge">預覽變更</button><button class="button destructive" data-action="commit-merge" id="merge-commit" disabled>合併並移除重複成員</button>');}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-close')){event.preventDefault();b.closest('dialog').close();return;}if(b.dataset.person){selectPerson(b.dataset.person,b.dataset.origin||'tree');return;}if(b.dataset.filter){memberFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));renderMembers();return;}if(b.dataset.version){selectedVersion=b.dataset.version;document.querySelectorAll('[data-version]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));$('version-commit').disabled=false;$('version-commit').textContent=selectedVersion==='local'?'保留此裝置，取代雲端':'使用雲端，取代此裝置';$('version-decision').textContent=selectedVersion==='local'?'此裝置的 14 位成員將取代雲端版本。請確認雲端新增的成員是否需要保留。':'雲端的 15 位成員將取代此裝置版本。取代前保留本機備份。';return;}const action=b.dataset.action;if(!action)return;event.preventDefault();if(!['more','form-more'].includes(action))closeMenus();switch(action){
case'members':openMembers();break;case'close-members':$('member-browser').hidden=true;updateBrowserIsolation();document.querySelector('[data-action=members]').focus();break;case'clear-search':$('member-search').value='';renderMembers();break;
case'more':$('global-menu').hidden=!$('global-menu').hidden;$('global-more-button').setAttribute('aria-expanded',String(!$('global-menu').hidden));break;
case'manage':utility('管理成員','<div class="management-grid"><button class="button" data-action="ranks"><span data-icon="list"></span>排行群組</button><button class="button" data-action="merge"><span data-icon="merge"></span>合併重複成員</button><button class="button" data-action="ignored">已忽略待補項目 <span class="badge">0</span></button></div>');break;
case'ignored':$('utility-dialog').close();utility('已忽略待補項目','<div class="empty-state">目前沒有已忽略的待補項目。<p class="helper">日後可在這裡恢復待補親屬。</p></div>');break;
case'ranks':case'merge':if($('utility-dialog').open)$('utility-dialog').close();action==='ranks'?openRanks():openMerge();break;
case'save-ranks':saveSnapshot('修改排行群組');$('utility-dialog').close();toast('已儲存示例排行群組',true);break;
case'preview-merge':{const keep=getPerson($('merge-keep').value),remove=getPerson($('merge-remove').value);$('merge-preview').hidden=false;if(keep.id===remove.id){$('merge-preview').innerHTML='<p class="field-error">請選擇兩位不同的成員。</p>';$('merge-commit').disabled=true;break;}$('merge-preview').innerHTML=`<div class="local-state"><span data-icon="info"></span><div><strong>保留${escapeHTML(keep.name)}，移除另一筆${escapeHTML(remove.name)}</strong><p>將整合重複關係。完成後可以復原。</p></div></div>`;hydrateIcons($('merge-preview'));$('merge-commit').disabled=false;break;}
case'commit-merge':{const keep=$('merge-keep').value,remove=$('merge-remove').value;saveSnapshot('合併重複成員');people=people.filter(p=>p.id!==remove);people.forEach(p=>{p.parents=p.parents.map(id=>id===remove?keep:id);if(p.spouse===remove)p.spouse=keep;});$('utility-dialog').close();renderAll();toast('已合併示例重複成員',true);break;}
case'edit':openEdit();break;case'add':openEdit(null);break;case'relative':openEdit(null,true);break;case'cancel-edit':requestEditClose();break;case'discard':$('discard-dialog').close();$('edit-dialog').close();toast('已捨棄這次表單修改');break;
case'form-more':$('form-menu').hidden=!$('form-menu').hidden;break;case'latest':$('form-conflict').hidden=false;break;
case'inspect-latest':utility('檢視最新資料','<p class="intro-copy">你的草稿仍保留在表單中。</p><div class="diff-row"><div><strong>職位</strong><span>原資料：教師 → 最新資料：退休教師</span></div></div><p class="helper" style="margin-top:16px">選擇載入最新資料，會捨棄目前的表單修改。</p>','<button class="button destructive" data-action="reload-edit">捨棄修改並載入</button><button class="button primary" data-action="keep-edit">保留目前修改</button>','版本更新');break;
case'keep-edit':$('utility-dialog').close();$('form-conflict').hidden=true;toast('目前修改已保留');break;case'reload-edit':$('utility-dialog').close();$('edit-name').value=getPerson(editId)?.name||'';$('edit-position').value='退休教師';$('form-conflict').hidden=true;baseline=formSnapshot();toast('已載入最新示例資料');break;
case'add-relation':$('edit-relations').insertAdjacentHTML('beforeend',relationRow('阿土','父親',true));updateRelation($('edit-relations').lastElementChild);break;case'toggle-relation':{const row=b.closest('.relation-edit-row'),controls=row.querySelector('.relation-controls');controls.hidden=!controls.hidden;b.setAttribute('aria-expanded',String(!controls.hidden));break;}case'remove-relation':removedRow=b.closest('.relation-edit-row');removedRow.remove();$('relation-removal').hidden=false;break;case'restore-relation':if(removedRow)$('edit-relations').append(removedRow);$('relation-removal').hidden=true;break;
case'close-detail':$('inspector').hidden=true;selectedId=null;renderTree();break;case'collapse-detail':$('inspector').classList.toggle('collapsed');break;case'detail-back':if(detailHistory.length){selectedId=detailHistory.pop();renderDetail();renderTree();}else{openMembers();if(innerWidth<=700)$('inspector').hidden=true;}break;
case'query':openQuery();break;case'swap':{const a=$('query-a').value;$('query-a').value=$('query-b').value;$('query-b').value=a;updateQuestion();break;}
case'end-query':queryActive=false;$('query-result').hidden=true;$('canvas-title').textContent='家的脈絡';$('canvas-subtitle').textContent='從一個名字，看見彼此的連結。';renderTree();fit();break;
case'path':{const path=queryPath.map(getPerson).filter(Boolean);utility('關係的依據',`<p class="intro-copy">${escapeHTML($('result-title').textContent)}</p><div class="path-card">${path.map(p=>escapeHTML(p.name)).join(' '+svg('chevron-right')+' ')}</div><p class="helper">這段稱謂依據已記錄的親子或配偶關係。未知的關係不會自動推定。</p>`,'','關係路徑');break;}
case'names':namesHidden=!namesHidden;const namesButton=$('names-button'),namesIcon=namesButton.querySelector('[data-icon]');namesIcon.dataset.icon=namesHidden?'eye-off':'eye';namesIcon.innerHTML=svg(namesIcon.dataset.icon);namesButton.querySelector('span:last-child').textContent=namesHidden?'顯示姓名':'隱藏姓名';namesButton.setAttribute('aria-label',namesHidden?'顯示畫布姓名':'隱藏畫布姓名');renderTree();break;case'legend':$('legend-popover').hidden=false;break;case'close-legend':$('legend-popover').hidden=true;break;
case'zoom-in':setScale(scale+.1);break;case'zoom-out':setScale(scale-.1);break;case'zoom-reset':setScale(1);break;case'fit':fit();break;
case'undo':{const last=undoStack.pop();if(!last){toast('目前沒有可以復原的修改');break;}people=last.people;if(!getPerson(selectedId))selectedId=people[0].id;renderAll();toast('已復原：'+last.label);break;}
case'close-toast':$('toast').hidden=true;break;case'sync':openDialog('sync-dialog');break;case'conflict':openConflict();break;case'sync-now':$('sync-dialog').close();toast('示例族譜已同步 · 本機資料已保存');break;case'disconnect':$('sync-dialog').close();toast('已中斷示例連結 · 本機資料仍保留');break;
case'commit-version':$('conflict-dialog').close();toast('已預覽版本取代完成 · 此模板不執行雲端操作');break;
case'import':utility('匯入族譜','<p class="intro-copy">匯入「陳氏家族備份.json」，將以 15 位成員取代目前的 14 位。</p><div class="difference-summary"><h3>變更摘要</h3><span class="diff-tag add">新增 1 位</span><span class="diff-tag change">修改 2 項</span></div><div class="local-state"><span data-icon="check"></span><div><strong>匯入前，保留此裝置的備份</strong><p>匯入後可復原這次取代。</p></div></div><p class="helper">示例檔案預覽，不會讀取或取代你的現有族譜。</p>','<button class="button" data-close>取消</button><button class="button destructive" data-action="confirm-import">取代此裝置族譜並匯入</button>','備份與同步');break;
case'confirm-import':saveSnapshot('匯入族譜');$('utility-dialog').close();toast('已預覽匯入完成',true);break;
case'export':{const blob=new Blob([JSON.stringify({schemaVersion:2,familyName:'陳氏家族（Layout示例）',people},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='family-layout-example.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已匯出示例資料');break;}
case'family-name':utility('編輯家族名稱','<label>家族名稱<input id="family-name-input" value="'+escapeHTML(document.querySelector('.identity h1').textContent)+'" maxlength="80"></label>','<button class="button" data-close>取消</button><button class="button primary" data-action="save-family-name">儲存名稱</button>','族譜設定');break;
case'save-family-name':{const name=$('family-name-input').value.trim();if(!name){$('family-name-input').focus();break;}document.querySelector('.identity h1').textContent=name;$('utility-dialog').close();toast('已更新示例家族名稱');break;}
}});
$('member-search').addEventListener('input',renderMembers);
for(const id of ['query-a','query-b'])$(id).addEventListener('change',updateQuestion);
$('query-form').addEventListener('submit',event=>{event.preventDefault();runQuery();});
$('edit-form').addEventListener('input',event=>{if(event.target.id==='edit-name'){$('name-error').textContent='';$('edit-name').removeAttribute('aria-invalid');}$('edit-relations').querySelectorAll('.relation-edit-row').forEach(updateRelation);});
$('edit-form').addEventListener('change',()=>{$('edit-relations').querySelectorAll('.relation-edit-row').forEach(updateRelation);});
$('edit-name').addEventListener('blur',()=>{const invalid=!$('edit-name').value.trim();$('name-error').textContent=invalid?'請填寫姓名。':'';$('edit-name').setAttribute('aria-invalid',String(invalid));$('edit-name').setAttribute('aria-describedby','name-error');});
$('edit-form').addEventListener('submit',event=>{event.preventDefault();const name=$('edit-name').value.trim();if(!name){$('name-error').textContent='請填寫姓名。';$('edit-name').focus();return;}saveSnapshot(editId?'修改'+name:'新增'+name);const p=getPerson(editId)||person('demo-'+Date.now(),name,$('edit-gender').value,null,'未設定關係');if(!editId)people.push(p);Object.assign(p,{name,gender:$('edit-gender').value,position:$('edit-position').value.trim(),notes:$('edit-notes').value.trim()});p.parents=[...$('edit-relations').children].filter(row=>['父親','母親'].includes(row.querySelector('.relation-role').value)).map(row=>row.querySelector('.relation-target').value);const spouse=[...$('edit-relations').children].find(row=>row.querySelector('.relation-role').value==='配偶');p.spouse=spouse?.querySelector('.relation-target').value||null;if(p.parents.length){p.gen=Math.max(...p.parents.map(id=>getPerson(id)?.gen||1))+1;}selectedId=p.id;$('edit-dialog').close();renderAll();$('inspector').hidden=false;toast('已儲存'+name+' · 此裝置',true);});
$('edit-dialog').addEventListener('cancel',event=>{event.preventDefault();requestEditClose();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!document.querySelector('dialog[open]')){if(!$('global-menu').hidden){closeMenus();$('global-more-button').focus();event.preventDefault();}else if(!$('legend-popover').hidden){closeMenus();event.preventDefault();}else if(!$('member-browser').hidden){$('member-browser').hidden=true;updateBrowserIsolation();document.querySelector('[data-action=members]').focus();event.preventDefault();}else if(!$('inspector').hidden){$('inspector').hidden=true;event.preventDefault();}}if((event.metaKey||event.ctrlKey)&&event.key==='z'&&!/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)&&!document.querySelector('dialog[open]')){event.preventDefault();document.querySelector('[data-action=undo]').click();}});
document.addEventListener('pointerdown',event=>{if(!event.target.closest('.popover,[data-action=more],[data-action=form-more]'))closeMenus();});
$('scope').addEventListener('change',()=>{toast($('scope').value==='family'?'已顯示陳阿土的家人':'已顯示所有關係');fit();});
window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==parent||event.data?.type!=='preview-scene')return;document.querySelectorAll('dialog[open]').forEach(d=>d.close());closeMenus();$('toast').hidden=true;switch(event.data.scene){case'tree':$('member-browser').hidden=true;$('query-result').hidden=true;queryActive=false;selectPerson('阿土');$('canvas-title').textContent='家的脈絡';$('canvas-subtitle').textContent='從一個名字，看見彼此的連結。';fit();break;case'members':$('inspector').hidden=true;openMembers();break;case'form':openEdit('文彬');break;case'query':openQuery();break;case'conflict':openConflict();break;}});
hydrateIcons();renderAll();
requestAnimationFrame(()=>{fit();if(innerWidth<=700)setScale(.64);});
new ResizeObserver(()=>{if(queryActive)renderTree();fit();if(innerWidth<=700&&!queryActive)setScale(.64);}).observe($('canvas'));
